language: python
python:
  - '2.7'
  - '3.5'
before_install:
  # Install last mosquitto version (version from 12.04 is not working)
  - sudo add-apt-repository -y ppa:mosquitto-dev/mosquitto-ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y mosquitto socat
install:
  - pip install tox-travis
script:
  - tox
addons:
  hosts:
    - localhost
notifications:
  email: false
